spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7e87e9177af43c53d68d3f6ab9
  expiration-ms: 86400000

rate-limit:
  capacity: 1000
  refill-per-minute: 1000
